In [1]:
import pandas as pd

In [12]:
df = pd.read_csv (r'C:\Users\trainee9\Desktop\Sohaib\dataset_9.csv',header =None)
df

C:\Users\trainee9\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (6,7,9,11,12,13,14,16,18,19) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,2021-08-26 17:47:13.727000+00:00,2.039297e+09,ARI6,1.630000e+09,"[""number to reach us"",""simply hang up""]",/NAS/airecordings/ARI6-1630000033.0-in.wav,Unnamed: 6,2021-10-23 16:45:38.441000+00:00,8.146763e+09,ARI7,1.635008e+09,"[""hello""]",/NAS/airecordings/ARI7-1635007538.16453-in.wav,"ARI7-1635007538.16453-in_0.wav,ARI7-1635007538...",2021-10-07 15:33:19.114000+00:00,3.344371e+09,ARI4,1.633621e+09,"[""sec""]",/NAS/airecordings/ARI4-1633620799.7394-in.wav
1,2021-10-04 18:05:31.995000+00:00,2.032331e+09,ARI1,1.633371e+09,"[""tone please record your message""]",/NAS/airecordings/ARI1-1633370731.25142-in.wav,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-10-04 18:05:32.218000+00:00,2.014372e+09,ARI1,1.633371e+09,"[""hello""]",/NAS/airecordings/ARI1-1633370732.25144-in.wav,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-10-04 18:05:32.855000+00:00,2.564858e+09,ARI4,1.633371e+09,"[""hello"",""alright"",""i dont have any credit car...",/NAS/airecordings/ARI4-1633370732.23168-in.wav,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-10-04 18:05:34.609000+00:00,5.594851e+09,ARI4,1.633371e+09,"[""hello"",""no i dont""]",/NAS/airecordings/ARI4-1633370734.23173-in.wav,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99996,2021-10-05 23:22:13.962000+00:00,5.615787e+09,ARI2,1.633476e+09,"[""unavailable please speak clearly your voice ...",/NAS/airecordings/ARI2-1633476133.9205-in.wav,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99997,2021-10-05 23:22:14.059000+00:00,9.793453e+09,ARI2,1.633476e+09,"[""hello"",""i dont try""]",/NAS/airecordings/ARI2-1633476134.9209-in.wav,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99998,2021-10-05 23:22:14.177000+00:00,7.138647e+09,ARI1,1.633476e+09,"[""at the tone please record your message when ...",/NAS/airecordings/ARI1-1633476134.9389-in.wav,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99999,2021-10-05 23:22:14.641000+00:00,7.407756e+09,ARI1,1.633476e+09,"[""i said hello""]",/NAS/airecordings/ARI1-1633476134.9395-in.wav,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100000,2021-10-05 23:22:15.171000+00:00,8.286894e+09,ARI1,1.633476e+09,"[""hello"",""hello""]",/NAS/airecordings/ARI1-1633476135.9397-in.wav,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df.dtypes

0      object
1     float64
2      object
3     float64
4      object
5      object
6      object
7      object
8     float64
9      object
10    float64
11     object
12     object
13     object
14     object
15    float64
16     object
17    float64
18     object
19     object
dtype: object

In [22]:
df.drop(df.columns[5:19], axis=1, inplace=True)

In [23]:
df

,0,1,2,3,4
0,2021-08-26 17:47:13.727000+00:00,2.039297e+09,ARI6,1.630000e+09,"[""number to reach us"",""simply hang up""]"
1,2021-10-04 18:05:31.995000+00:00,2.032331e+09,ARI1,1.633371e+09,"[""tone please record your message""]"
2,2021-10-04 18:05:32.218000+00:00,2.014372e+09,ARI1,1.633371e+09,"[""hello""]"
3,2021-10-04 18:05:32.855000+00:00,2.564858e+09,ARI4,1.633371e+09,"[""hello"",""alright"",""i dont have any credit car..."
4,2021-10-04 18:05:34.609000+00:00,5.594851e+09,ARI4,1.633371e+09,"[""hello"",""no i dont""]"
...,...,...,...,...,...
99996,2021-10-05 23:22:13.962000+00:00,5.615787e+09,ARI2,1.633476e+09,"[""unavailable please speak clearly your voice ..."
99997,2021-10-05 23:22:14.059000+00:00,9.793453e+09,ARI2,1.633476e+09,"[""hello"",""i dont try""]"
99998,2021-10-05 23:22:14.177000+00:00,7.138647e+09,ARI1,1.633476e+09,"[""at the tone please record your message when ..."
99999,2021-10-05 23:22:14.641000+00:00,7.407756e+09,ARI1,1.633476e+09,"[""i said hello""]"
100000,2021-10-05 23:22:15.171000+00:00,8.286894e+09,ARI1,1.633476e+09,"[""hello"",""hello""]"

In [24]:
df.rename(columns={'0': 'data.timestamp'})

,0,1,2,3,4
0,2021-08-26 17:47:13.727000+00:00,2.039297e+09,ARI6,1.630000e+09,"[""number to reach us"",""simply hang up""]"
1,2021-10-04 18:05:31.995000+00:00,2.032331e+09,ARI1,1.633371e+09,"[""tone please record your message""]"
2,2021-10-04 18:05:32.218000+00:00,2.014372e+09,ARI1,1.633371e+09,"[""hello""]"
3,2021-10-04 18:05:32.855000+00:00,2.564858e+09,ARI4,1.633371e+09,"[""hello"",""alright"",""i dont have any credit car..."
4,2021-10-04 18:05:34.609000+00:00,5.594851e+09,ARI4,1.633371e+09,"[""hello"",""no i dont""]"
...,...,...,...,...,...
99996,2021-10-05 23:22:13.962000+00:00,5.615787e+09,ARI2,1.633476e+09,"[""unavailable please speak clearly your voice ..."
99997,2021-10-05 23:22:14.059000+00:00,9.793453e+09,ARI2,1.633476e+09,"[""hello"",""i dont try""]"
99998,2021-10-05 23:22:14.177000+00:00,7.138647e+09,ARI1,1.633476e+09,"[""at the tone please record your message when ..."
99999,2021-10-05 23:22:14.641000+00:00,7.407756e+09,ARI1,1.633476e+09,"[""i said hello""]"
100000,2021-10-05 23:22:15.171000+00:00,8.286894e+09,ARI1,1.633476e+09,"[""hello"",""hello""]"

In [34]:
df.columns=['data.timestamp','data.number','data.application','data.id', 'data.rawTranscriptions']
df

,data.timestamp,data.number,data.application,data.id,data.rawTranscriptions
0,2021-08-26 17:47:13.727000+00:00,2.039297e+09,ARI6,1.630000e+09,"[""number to reach us"",""simply hang up""]"
1,2021-10-04 18:05:31.995000+00:00,2.032331e+09,ARI1,1.633371e+09,"[""tone please record your message""]"
2,2021-10-04 18:05:32.218000+00:00,2.014372e+09,ARI1,1.633371e+09,"[""hello""]"
3,2021-10-04 18:05:32.855000+00:00,2.564858e+09,ARI4,1.633371e+09,"[""hello"",""alright"",""i dont have any credit car..."
4,2021-10-04 18:05:34.609000+00:00,5.594851e+09,ARI4,1.633371e+09,"[""hello"",""no i dont""]"
...,...,...,...,...,...
99996,2021-10-05 23:22:13.962000+00:00,5.615787e+09,ARI2,1.633476e+09,"[""unavailable please speak clearly your voice ..."
99997,2021-10-05 23:22:14.059000+00:00,9.793453e+09,ARI2,1.633476e+09,"[""hello"",""i dont try""]"
99998,2021-10-05 23:22:14.177000+00:00,7.138647e+09,ARI1,1.633476e+09,"[""at the tone please record your message when ..."
99999,2021-10-05 23:22:14.641000+00:00,7.407756e+09,ARI1,1.633476e+09,"[""i said hello""]"
100000,2021-10-05 23:22:15.171000+00:00,8.286894e+09,ARI1,1.633476e+09,"[""hello"",""hello""]"

In [35]:
df.head(10)

,data.timestamp,data.number,data.application,data.id,data.rawTranscriptions
0,2021-08-26 17:47:13.727000+00:00,2.039297e+09,ARI6,1.630000e+09,"[""number to reach us"",""simply hang up""]"
1,2021-10-04 18:05:31.995000+00:00,2.032331e+09,ARI1,1.633371e+09,"[""tone please record your message""]"
2,2021-10-04 18:05:32.218000+00:00,2.014372e+09,ARI1,1.633371e+09,"[""hello""]"
3,2021-10-04 18:05:32.855000+00:00,2.564858e+09,ARI4,1.633371e+09,"[""hello"",""alright"",""i dont have any credit car..."
4,2021-10-04 18:05:34.609000+00:00,5.594851e+09,ARI4,1.633371e+09,"[""hello"",""no i dont""]"
5,2021-10-04 18:05:34.640000+00:00,3.365587e+09,ARI5,1.633371e+09,"[""six"",""thank"",""if you are satisfied with your..."
6,2021-10-04 18:05:36.022000+00:00,8.459471e+09,ARI4,1.633371e+09,"[""who this"",""what is about"",""i dont i dont hav..."
7,2021-10-04 18:05:36.107000+00:00,5.182804e+09,ARI3,1.633371e+09,"[""and phone number after the beep""]"
8,2021-10-04 18:05:36.405000+00:00,4.135256e+09,ARI3,1.633371e+09,"[""and elaine at five two five"",""five eight"",""oh""]"
9,2021-10-04 18:05:36.462000+00:00,5.413326e+09,ARI3,1.633371e+09,"[""what are you selling"",""executor""]"

In [40]:
df['data.rawTranscriptions'][0]

'["number to reach us","simply hang up"]'

In [43]:
df['data.rawTranscriptions'] = df['data.rawTranscriptions'].apply(lambda x: json.loads(x))

In [44]:
df

,data.timestamp,data.number,data.application,data.id,data.rawTranscriptions
0,2021-08-26 17:47:13.727000+00:00,2.039297e+09,ARI6,1.630000e+09,"[number to reach us, simply hang up]"
1,2021-10-04 18:05:31.995000+00:00,2.032331e+09,ARI1,1.633371e+09,[tone please record your message]
2,2021-10-04 18:05:32.218000+00:00,2.014372e+09,ARI1,1.633371e+09,[hello]
3,2021-10-04 18:05:32.855000+00:00,2.564858e+09,ARI4,1.633371e+09,"[hello, alright, i dont have any credit cards]"
4,2021-10-04 18:05:34.609000+00:00,5.594851e+09,ARI4,1.633371e+09,"[hello, no i dont]"
...,...,...,...,...,...
99996,2021-10-05 23:22:13.962000+00:00,5.615787e+09,ARI2,1.633476e+09,[unavailable please speak clearly your voice m...
99997,2021-10-05 23:22:14.059000+00:00,9.793453e+09,ARI2,1.633476e+09,"[hello, i dont try]"
99998,2021-10-05 23:22:14.177000+00:00,7.138647e+09,ARI1,1.633476e+09,[at the tone please record your message when y...
99999,2021-10-05 23:22:14.641000+00:00,7.407756e+09,ARI1,1.633476e+09,[i said hello]
100000,2021-10-05 23:22:15.171000+00:00,8.286894e+09,ARI1,1.633476e+09,"[hello, hello]"

In [63]:
df=df.explode('data.rawTranscriptions')

In [64]:
df

,data.timestamp,data.number,data.application,data.id,data.rawTranscriptions
0,2021-08-26 17:47:13.727000+00:00,2.039297e+09,ARI6,1630000033,number to reach us
0,2021-08-26 17:47:13.727000+00:00,2.039297e+09,ARI6,1630000033,simply hang up
1,2021-10-04 18:05:31.995000+00:00,2.032331e+09,ARI1,1633370731,tone please record your message
2,2021-10-04 18:05:32.218000+00:00,2.014372e+09,ARI1,1633370732,hello
3,2021-10-04 18:05:32.855000+00:00,2.564858e+09,ARI4,1633370732,hello
...,...,...,...,...,...
99997,2021-10-05 23:22:14.059000+00:00,9.793453e+09,ARI2,1633476134,i dont try
99998,2021-10-05 23:22:14.177000+00:00,7.138647e+09,ARI1,1633476134,at the tone please record your message when yo...
99999,2021-10-05 23:22:14.641000+00:00,7.407756e+09,ARI1,1633476134,i said hello
100000,2021-10-05 23:22:15.171000+00:00,8.286894e+09,ARI1,1633476135,hello
100000,2021-10-05 23:22:15.171000+00:00,8.286894e+09,ARI1,1633476135,hello

In [68]:
df['data.number']=df['data.number'].astype(int)

In [69]:
df

,data.timestamp,data.number,data.application,data.id,data.rawTranscriptions
0,2021-08-26 17:47:13.727000+00:00,2039297081,ARI6,1630000033,number to reach us
0,2021-08-26 17:47:13.727000+00:00,2039297081,ARI6,1630000033,simply hang up
1,2021-10-04 18:05:31.995000+00:00,2032331188,ARI1,1633370731,tone please record your message
2,2021-10-04 18:05:32.218000+00:00,2014372398,ARI1,1633370732,hello
3,2021-10-04 18:05:32.855000+00:00,-2147483648,ARI4,1633370732,hello
...,...,...,...,...,...
99997,2021-10-05 23:22:14.059000+00:00,-2147483648,ARI2,1633476134,i dont try
99998,2021-10-05 23:22:14.177000+00:00,-2147483648,ARI1,1633476134,at the tone please record your message when yo...
99999,2021-10-05 23:22:14.641000+00:00,-2147483648,ARI1,1633476134,i said hello
100000,2021-10-05 23:22:15.171000+00:00,-2147483648,ARI1,1633476135,hello
100000,2021-10-05 23:22:15.171000+00:00,-2147483648,ARI1,1633476135,hello

In [77]:
df["audioname"] = df["data.application"].astype(str)+'-' + df["data.id"].astype(str)+'-in.wav'

In [78]:
df

,data.timestamp,data.number,data.application,data.id,data.rawTranscriptions,audioname
0,2021-08-26 17:47:13.727000+00:00,2039297081,ARI6,1630000033,number to reach us,ARI6-1630000033-in.wav
0,2021-08-26 17:47:13.727000+00:00,2039297081,ARI6,1630000033,simply hang up,ARI6-1630000033-in.wav
1,2021-10-04 18:05:31.995000+00:00,2032331188,ARI1,1633370731,tone please record your message,ARI1-1633370731-in.wav
2,2021-10-04 18:05:32.218000+00:00,2014372398,ARI1,1633370732,hello,ARI1-1633370732-in.wav
3,2021-10-04 18:05:32.855000+00:00,-2147483648,ARI4,1633370732,hello,ARI4-1633370732-in.wav
...,...,...,...,...,...,...
99997,2021-10-05 23:22:14.059000+00:00,-2147483648,ARI2,1633476134,i dont try,ARI2-1633476134-in.wav
99998,2021-10-05 23:22:14.177000+00:00,-2147483648,ARI1,1633476134,at the tone please record your message when yo...,ARI1-1633476134-in.wav
99999,2021-10-05 23:22:14.641000+00:00,-2147483648,ARI1,1633476134,i said hello,ARI1-1633476134-in.wav
100000,2021-10-05 23:22:15.171000+00:00,-2147483648,ARI1,1633476135,hello,ARI1-1633476135-in.wav
100000,2021-10-05 23:22:15.171000+00:00,-2147483648,ARI1,1633476135,hello,ARI1-1633476135-in.wav

In [84]:
df.head(10)

,data.timestamp,data.number,data.application,data.id,data.rawTranscriptions,audioname
0,2021-08-26 17:47:13.727000+00:00,2039297081,ARI6,1630000033,number to reach us,ARI6-1630000033-in.wav
0,2021-08-26 17:47:13.727000+00:00,2039297081,ARI6,1630000033,simply hang up,ARI6-1630000033-in.wav
1,2021-10-04 18:05:31.995000+00:00,2032331188,ARI1,1633370731,tone please record your message,ARI1-1633370731-in.wav
2,2021-10-04 18:05:32.218000+00:00,2014372398,ARI1,1633370732,hello,ARI1-1633370732-in.wav
3,2021-10-04 18:05:32.855000+00:00,-2147483648,ARI4,1633370732,hello,ARI4-1633370732-in.wav
3,2021-10-04 18:05:32.855000+00:00,-2147483648,ARI4,1633370732,alright,ARI4-1633370732-in.wav
3,2021-10-04 18:05:32.855000+00:00,-2147483648,ARI4,1633370732,i dont have any credit cards,ARI4-1633370732-in.wav
4,2021-10-04 18:05:34.609000+00:00,-2147483648,ARI4,1633370734,hello,ARI4-1633370734-in.wav
4,2021-10-04 18:05:34.609000+00:00,-2147483648,ARI4,1633370734,no i dont,ARI4-1633370734-in.wav
5,2021-10-04 18:05:34.640000+00:00,-2147483648,ARI5,1633370734,six,ARI5-1633370734-in.wav